# Generated by Django 5.2.17 on 2026-09-27 15:45

import django.db.models.deletion
from django.db import migrations, models

import config.db
import config.run_id


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("keywords", "0001_initial"),
        ("sites", "0001_initial"),
    ]

    operations = [
        # Типы-перечисления из schema.sql (ADR-029). Добавлены вручную:
        # makemigrations их не знает. Значения совпадают с TextChoices
        # в apps/placements/models.py — это проверяет tests/test_schema_parity.py.
        # anchor_type для ссылок создан в keywords.0001.
        migrations.RunSQL(
            sql=[
                "CREATE TYPE placement_status AS ENUM"
                " ('planned','ordered','writing','review','published','rejected','cancelled')",
                "CREATE TYPE placement_type AS ENUM ('guest_post','link_insertion')",
            ],
            reverse_sql=[
                "DROP TYPE placement_type",
                "DROP TYPE placement_status",
            ],
        ),
        migrations.CreateModel(
            name="Placement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "article_url",
                    models.TextField(blank=True, null=True, verbose_name="адрес статьи"),
                ),
                (
                    "status",
                    config.db.PgEnumField(
                        choices=[
                            ("planned", "Запланировано"),
                            ("ordered", "Заявка отправлена"),
                            ("writing", "Пишется"),
                            ("review", "На проверке"),
                            ("published", "Опубликовано"),
                            ("rejected", "Отклонено"),
                            ("cancelled", "Отменено"),
                        ],
                        db_default="planned",
                        default="planned",
                        enum_type="placement_status",
                        verbose_name="статус",
                    ),
                ),
                (
                    "collaborator_order_id",
                    models.TextField(blank=True, null=True, verbose_name="номер заявки"),
                ),
                (
                    "placement_type",
                    config.db.PgEnumField(
                        blank=True,
                        choices=[
                            ("guest_post", "Guest Post"),
                            ("link_insertion", "Link Insertion"),
                        ],
                        enum_type="placement_type",
                        null=True,
                        verbose_name="тип размещения",
                    ),
                ),
                (
                    "ad_label_requested",
                    models.BooleanField(
                        db_default=False,
                        default=False,
                        help_text="Тогда пометка «реклама» в статье — не нарушение.",
                        verbose_name="пометку «реклама» заказали мы",
                    ),
                ),
                (
                    "ordered_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="заявка отправлена"),
                ),
                (
                    "published_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="опубликовано"),
                ),
                (
                    "price_paid_cents",
                    models.IntegerField(blank=True, null=True, verbose_name="заплачено, центы"),
                ),
                (
                    "currency",
                    models.CharField(
                        blank=True,
                        db_default="EUR",
                        default="EUR",
                        max_length=3,
                        null=True,
                        verbose_name="валюта",
                    ),
                ),
                (
                    "is_indexed",
                    models.BooleanField(
                        blank=True,
                        help_text="Пусто — не проверялось.",
                        null=True,
                        verbose_name="в индексе",
                    ),
                ),
                (
                    "indexed_checked_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="индексация проверена"
                    ),
                ),
                (
                    "announce_on_homepage",
                    models.BooleanField(blank=True, null=True, verbose_name="анонс на главной"),
                ),
                (
                    "clicks_from_homepage",
                    models.SmallIntegerField(
                        blank=True, null=True, verbose_name="кликов от главной"
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        help_text="Что не так с полученной статьёй.",
                        null=True,
                        verbose_name="комментарий",
                    ),
                ),
                (
                    "run_id",
                    models.UUIDField(
                        blank=True,
                        default=config.run_id.current_run_id,
                        null=True,
                        verbose_name="run_id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(db_default=config.db.PgNow(), verbose_name="создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_default=config.db.PgNow(), verbose_name="изменено"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="placements",
                        to="sites.product",
                        verbose_name="продукт",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="placements",
                        to="sites.site",
                        verbose_name="площадка",
                    ),
                ),
            ],
            options={
                "verbose_name": "размещение",
                "verbose_name_plural": "размещения",
                "db_table": "placements",
            },
        ),
        migrations.CreateModel(
            name="PlacementLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("anchor", models.TextField(verbose_name="анкор")),
                ("target_url", models.TextField(verbose_name="куда ведёт")),
                (
                    "anchor_type",
                    config.db.PgEnumField(
                        blank=True,
                        choices=[
                            ("exact", "Прямой"),
                            ("diluted", "Разбавленный"),
                            ("branded", "Бренд"),
                            ("url", "Голый адрес"),
                            ("generic", "Нейтральное слово"),
                        ],
                        enum_type="anchor_type",
                        null=True,
                        verbose_name="тип анкора",
                    ),
                ),
                (
                    "rel",
                    models.TextField(
                        blank=True,
                        help_text="Атрибут на странице; пусто — нет, dofollow.",
                        null=True,
                        verbose_name="rel",
                    ),
                ),
                (
                    "char_offset",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="знаков до ссылки, с пробелами"
                    ),
                ),
                (
                    "char_offset_no_spaces",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="знаков до ссылки, без пробелов"
                    ),
                ),
                (
                    "context_sentence",
                    models.TextField(blank=True, null=True, verbose_name="предложение со ссылкой"),
                ),
                (
                    "link_index",
                    models.SmallIntegerField(blank=True, null=True, verbose_name="номер ссылки"),
                ),
                (
                    "extraction_test_passed",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="тест на извлечение пройден"
                    ),
                ),
                (
                    "is_alive",
                    models.BooleanField(blank=True, null=True, verbose_name="ссылка на месте"),
                ),
                (
                    "last_checked_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="проверена"),
                ),
                (
                    "first_seen_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="появилась"),
                ),
                ("lost_at", models.DateTimeField(blank=True, null=True, verbose_name="пропала")),
                (
                    "keyword",
                    models.ForeignKey(
                        blank=True,
                        db_index=False,
                        help_text="Пусто — безанкорная или брендовая ссылка.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="links",
                        to="keywords.keyword",
                        verbose_name="ключ",
                    ),
                ),
                (
                    "placement",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="links",
                        to="placements.placement",
                        verbose_name="размещение",
                    ),
                ),
            ],
            options={
                "verbose_name": "ссылка",
                "verbose_name_plural": "ссылки",
                "db_table": "placement_links",
            },
        ),
        migrations.AddIndex(
            model_name="placement",
            index=models.Index(fields=["site", "product"], name="idx_placements_site"),
        ),
        migrations.AddIndex(
            model_name="placement",
            index=models.Index(fields=["status"], name="idx_placements_status"),
        ),
        migrations.AddIndex(
            model_name="placement",
            index=models.Index(fields=["-published_at"], name="idx_placements_pub"),
        ),
        migrations.AddIndex(
            model_name="placementlink",
            index=models.Index(fields=["placement"], name="idx_links_placement"),
        ),
        migrations.AddIndex(
            model_name="placementlink",
            index=models.Index(fields=["keyword"], name="idx_links_keyword"),
        ),
        migrations.AddIndex(
            model_name="placementlink",
            index=models.Index(fields=["is_alive", "last_checked_at"], name="idx_links_health"),
        ),
    ]
