# Generated by Django 5.2.17 on 2026-10-01 10:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("placements", "0002_views"),
    ]

    operations = [
        migrations.AddField(
            model_name="placement",
            name="skip_checks",
            field=models.BooleanField(
                db_default=False,
                default=False,
                help_text="Статья больше не нужна: система не проверяет её по расписанию. Проверить вручную можно и так.",
                verbose_name="не проверять",
            ),
        ),
    ]
