# Generated by Django 5.2.17 on 2026-10-01 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import config.db


class Migration(migrations.Migration):
    dependencies = [
        ("placements", "0003_skip_checks"),
        ("sites", "0008_offers_required"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="placement",
            name="employee",
            field=models.ForeignKey(
                blank=True,
                db_index=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="placements",
                to=settings.AUTH_USER_MODEL,
                verbose_name="сотрудник",
            ),
        ),
        migrations.AddField(
            model_name="placement",
            name="seller",
            field=models.ForeignKey(
                blank=True,
                db_index=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="placements",
                to="sites.seller",
                verbose_name="продавец",
            ),
        ),
        migrations.AlterField(
            model_name="placement",
            name="placement_type",
            field=config.db.PgEnumField(
                blank=True,
                choices=[("guest_post", "публикация"), ("link_insertion", "вставка ссылки")],
                enum_type="placement_type",
                null=True,
                verbose_name="тип размещения",
            ),
        ),
    ]
