# Generated by Django 5.2.17 on 2026-10-03 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import config.db


class Migration(migrations.Migration):
    dependencies = [
        ("placements", "0004_seller_employee"),
        ("sites", "0016_status_changes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlacementStatusChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "from_status",
                    config.db.PgEnumField(
                        blank=True,
                        choices=[
                            ("planned", "Запланировано"),
                            ("ordered", "Заявка отправлена"),
                            ("writing", "Пишется"),
                            ("review", "На проверке"),
                            ("published", "Опубликовано"),
                            ("rejected", "Отклонено"),
                            ("cancelled", "Отменено"),
                        ],
                        enum_type="placement_status",
                        null=True,
                        verbose_name="был",
                    ),
                ),
                (
                    "to_status",
                    config.db.PgEnumField(
                        choices=[
                            ("planned", "Запланировано"),
                            ("ordered", "Заявка отправлена"),
                            ("writing", "Пишется"),
                            ("review", "На проверке"),
                            ("published", "Опубликовано"),
                            ("rejected", "Отклонено"),
                            ("cancelled", "Отменено"),
                        ],
                        enum_type="placement_status",
                        verbose_name="стал",
                    ),
                ),
                (
                    "source",
                    config.db.PgEnumField(
                        blank=True,
                        choices=[
                            ("panel", "панель"),
                            ("form", "форма"),
                            ("placement", "по размещению"),
                            ("import", "импорт таблицы"),
                            ("upload", "загрузка"),
                            ("migration", "миграция"),
                        ],
                        enum_type="status_source",
                        null=True,
                        verbose_name="откуда",
                    ),
                ),
                ("run_id", models.UUIDField(blank=True, null=True, verbose_name="run_id")),
                (
                    "changed_at",
                    models.DateTimeField(db_default=config.db.PgNow(), verbose_name="когда"),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="кто",
                    ),
                ),
                (
                    "placement",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="status_changes",
                        to="placements.placement",
                        verbose_name="размещение",
                    ),
                ),
            ],
            options={
                "verbose_name": "смена статуса размещения",
                "verbose_name_plural": "история статусов размещений",
                "db_table": "placement_status_changes",
                "indexes": [
                    models.Index(
                        fields=["placement", "-changed_at"], name="idx_placement_status_changes"
                    )
                ],
            },
        ),
        # Триггер пишет строку истории при каждой смене статуса и при создании
        # размещения (ADR-049); текст — как в schema.sql.
        migrations.RunSQL(
            sql=[
                """
CREATE FUNCTION log_placement_status_change() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    INSERT INTO placement_status_changes
        (placement_id, from_status, to_status, source, actor_id, run_id)
    VALUES (
        NEW.id,
        CASE WHEN TG_OP = 'UPDATE' THEN OLD.status END,
        NEW.status,
        NULLIF(current_setting('seo.change_source', true), '')::status_source,
        NULLIF(current_setting('seo.change_actor', true), '')::integer,
        NULLIF(current_setting('seo.change_run_id', true), '')::uuid
    );
    RETURN NULL;
END
$$
""",
                "CREATE TRIGGER placements_status_insert AFTER INSERT ON placements"
                " FOR EACH ROW EXECUTE FUNCTION log_placement_status_change()",
                "CREATE TRIGGER placements_status_update AFTER UPDATE OF status ON placements"
                " FOR EACH ROW WHEN (OLD.status IS DISTINCT FROM NEW.status)"
                " EXECUTE FUNCTION log_placement_status_change()",
            ],
            reverse_sql=[
                "DROP TRIGGER placements_status_update ON placements",
                "DROP TRIGGER placements_status_insert ON placements",
                "DROP FUNCTION log_placement_status_change()",
            ],
        ),
    ]
