# Generated by Django 5.2.17 on 2026-10-04 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import config.db


class Migration(migrations.Migration):
    dependencies = [
        ("placements", "0006_extra"),
        ("sites", "0018_uploads_placements_refdomains"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Тип статуса счёта из schema.sql (ADR-029, ADR-055) — вручную:
        # makemigrations типы-перечисления не знает.
        migrations.RunSQL(
            sql="CREATE TYPE invoice_status AS ENUM ('issued','paid','cancelled')",
            reverse_sql="DROP TYPE invoice_status",
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "number",
                    models.TextField(
                        blank=True,
                        help_text="Как у продавца, если есть.",
                        null=True,
                        verbose_name="номер счёта",
                    ),
                ),
                ("amount_cents", models.IntegerField(verbose_name="сумма, центы")),
                (
                    "currency",
                    models.CharField(
                        db_default="EUR", default="EUR", max_length=3, verbose_name="валюта"
                    ),
                ),
                (
                    "pay_url",
                    models.TextField(
                        blank=True,
                        help_text="Счёт PayPal или другая страница оплаты.",
                        null=True,
                        verbose_name="ссылка на оплату",
                    ),
                ),
                (
                    "issued_on",
                    models.DateField(
                        db_default=config.db.PgCurrentDate(), verbose_name="выставлен"
                    ),
                ),
                (
                    "status",
                    config.db.PgEnumField(
                        choices=[
                            ("issued", "Выставлен"),
                            ("paid", "Оплачен"),
                            ("cancelled", "Отменён"),
                        ],
                        db_default="issued",
                        default="issued",
                        enum_type="invoice_status",
                        verbose_name="статус",
                    ),
                ),
                ("paid_on", models.DateField(blank=True, null=True, verbose_name="оплачен")),
                ("comment", models.TextField(blank=True, null=True, verbose_name="комментарий")),
                (
                    "created_at",
                    models.DateTimeField(db_default=config.db.PgNow(), verbose_name="заведён"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_default=config.db.PgNow(), verbose_name="изменён"
                    ),
                ),
                (
                    "paid_by",
                    models.ForeignKey(
                        blank=True,
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="оплатил",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to="sites.seller",
                        verbose_name="продавец",
                    ),
                ),
            ],
            options={
                "verbose_name": "счёт",
                "verbose_name_plural": "счета",
                "db_table": "invoices",
            },
        ),
        migrations.CreateModel(
            name="InvoiceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("amount_cents", models.IntegerField(verbose_name="доля, центы")),
                (
                    "invoice",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="placements.invoice",
                        verbose_name="счёт",
                    ),
                ),
                (
                    "placement",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoice_items",
                        to="placements.placement",
                        verbose_name="размещение",
                    ),
                ),
            ],
            options={
                "verbose_name": "строка счёта",
                "verbose_name_plural": "строки счёта",
                "db_table": "invoice_items",
            },
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(fields=["seller", "status"], name="idx_invoices_seller"),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount_cents__gt", 0)),
                name="invoices_amount_cents_check",
                violation_error_message="Сумма счёта — больше нуля.",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.UniqueConstraint(
                condition=models.Q(("pay_url__isnull", False)),
                fields=("pay_url",),
                name="invoices_pay_url_key",
                violation_error_message="Счёт с этой ссылкой на оплату уже есть.",
            ),
        ),
        migrations.AddIndex(
            model_name="invoiceitem",
            index=models.Index(fields=["placement"], name="idx_invoice_items_placement"),
        ),
        migrations.AddConstraint(
            model_name="invoiceitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount_cents__gte", 0)),
                name="invoice_items_amount_cents_check",
                violation_error_message="Доля не может быть меньше нуля.",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoiceitem",
            constraint=models.UniqueConstraint(
                fields=("invoice", "placement"),
                name="invoice_items_invoice_id_placement_id_key",
                violation_error_message="Это размещение уже в счёте.",
            ),
        ),
    ]
