# Generated by Django 5.2.17 on 2026-09-27 15:15

import django.db.models.deletion
from django.db import migrations, models

import config.db


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("sites", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PromptTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("task", models.TextField(verbose_name="задача")),
                ("name", models.TextField(verbose_name="название")),
                (
                    "is_active",
                    models.BooleanField(db_default=True, default=True, verbose_name="активен"),
                ),
                (
                    "created_at",
                    models.DateTimeField(db_default=config.db.PgNow(), verbose_name="создан"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="prompt_templates",
                        to="sites.product",
                        verbose_name="продукт",
                    ),
                ),
            ],
            options={
                "verbose_name": "шаблон промпта",
                "verbose_name_plural": "шаблоны промптов",
                "db_table": "prompt_templates",
            },
        ),
        migrations.CreateModel(
            name="PromptVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("label", models.TextField(verbose_name="метка")),
                ("body", models.TextField(verbose_name="текст промпта")),
                (
                    "times_used",
                    models.IntegerField(db_default=0, default=0, verbose_name="использован, раз"),
                ),
                (
                    "times_accepted",
                    models.IntegerField(db_default=0, default=0, verbose_name="принят, раз"),
                ),
                (
                    "is_active",
                    models.BooleanField(db_default=True, default=True, verbose_name="активен"),
                ),
                (
                    "created_at",
                    models.DateTimeField(db_default=config.db.PgNow(), verbose_name="создан"),
                ),
                (
                    "template",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="variants",
                        to="content.prompttemplate",
                        verbose_name="шаблон",
                    ),
                ),
            ],
            options={
                "verbose_name": "вариант промпта",
                "verbose_name_plural": "варианты промптов",
                "db_table": "prompt_variants",
            },
        ),
    ]
