# Generated by Django 5.2.17 on 2026-09-28 15:30

import django.db.models.deletion
from django.db import migrations, models

import config.db


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0001_initial"),
        ("sites", "0002_site_lists"),
    ]

    operations = [
        migrations.CreateModel(
            name="DomainSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("key", models.TextField(verbose_name="ключ")),
                ("value", models.JSONField(verbose_name="значение")),
                ("description", models.TextField(blank=True, null=True, verbose_name="описание")),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_default=config.db.PgNow(), verbose_name="изменена"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="domain_settings",
                        to="sites.product",
                        verbose_name="продукт",
                    ),
                ),
            ],
            options={
                "verbose_name": "настройка",
                "verbose_name_plural": "настройки",
                "db_table": "domain_settings",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("key", "product"),
                        name="domain_settings_key_product_id_key",
                        nulls_distinct=False,
                        violation_error_message="Эта настройка у этого продукта уже есть.",
                    )
                ],
            },
        ),
    ]
