# Generated by Django 5.2.17 on 2026-09-27 15:44

import django.db.models.deletion
from django.db import migrations, models

import config.db


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("sites", "0001_initial"),
    ]

    operations = [
        # Тип-перечисление из schema.sql (ADR-029). Добавлен вручную:
        # makemigrations его не знает. Значения совпадают с AnchorType
        # в apps/keywords/models.py — это проверяет tests/test_schema_parity.py.
        # anchor_type нужен и ссылкам размещений: миграция placements.0001
        # зависит от этой. metric_source для позиций создан в sites.0001.
        migrations.RunSQL(
            sql="CREATE TYPE anchor_type AS ENUM ('exact','diluted','branded','url','generic')",
            reverse_sql="DROP TYPE anchor_type",
        ),
        migrations.CreateModel(
            name="Keyword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("keyword", models.TextField(verbose_name="ключ")),
                ("target_url", models.TextField(verbose_name="целевая страница")),
                ("volume", models.IntegerField(blank=True, null=True, verbose_name="объём")),
                (
                    "global_volume",
                    models.IntegerField(blank=True, null=True, verbose_name="глобальный объём"),
                ),
                ("tool", models.TextField(blank=True, null=True, verbose_name="раздел сайта")),
                ("page_type", models.TextField(blank=True, null=True, verbose_name="тип страницы")),
                (
                    "anchor_type",
                    config.db.PgEnumField(
                        blank=True,
                        choices=[
                            ("exact", "Прямой"),
                            ("diluted", "Разбавленный"),
                            ("branded", "Бренд"),
                            ("url", "Голый адрес"),
                            ("generic", "Нейтральное слово"),
                        ],
                        enum_type="anchor_type",
                        null=True,
                        verbose_name="тип анкора",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(db_default=True, default=True, verbose_name="активен"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="keywords",
                        to="sites.product",
                        verbose_name="продукт",
                    ),
                ),
            ],
            options={
                "verbose_name": "ключ",
                "verbose_name_plural": "ключи",
                "db_table": "keywords",
            },
        ),
        migrations.CreateModel(
            name="KeywordPosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "position",
                    models.SmallIntegerField(
                        blank=True,
                        help_text="Пусто — вне топ-100.",
                        null=True,
                        verbose_name="позиция",
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        db_default="US", default="US", max_length=2, verbose_name="страна"
                    ),
                ),
                (
                    "source",
                    config.db.PgEnumField(
                        choices=[
                            ("ahrefs_api", "Ahrefs API"),
                            ("serp_api", "SERP API"),
                            ("manual", "Вручную"),
                            ("csv_import", "Импорт из файла"),
                            ("collaborator_api", "Collaborator API"),
                        ],
                        db_default="ahrefs_api",
                        default="ahrefs_api",
                        enum_type="metric_source",
                        verbose_name="источник",
                    ),
                ),
                (
                    "checked_at",
                    models.DateField(db_default=config.db.PgCurrentDate(), verbose_name="дата"),
                ),
                (
                    "keyword",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="positions",
                        to="keywords.keyword",
                        verbose_name="ключ",
                    ),
                ),
            ],
            options={
                "verbose_name": "позиция ключа",
                "verbose_name_plural": "позиции ключей",
                "db_table": "keyword_positions",
            },
        ),
        migrations.AddIndex(
            model_name="keyword",
            index=models.Index(
                condition=models.Q(("is_active", True)), fields=["tool"], name="idx_keywords_tool"
            ),
        ),
        migrations.AddConstraint(
            model_name="keyword",
            constraint=models.UniqueConstraint(
                fields=("product", "keyword"),
                name="keywords_product_id_keyword_key",
                violation_error_message="Такой ключ у этого продукта уже есть.",
            ),
        ),
        migrations.AddIndex(
            model_name="keywordposition",
            index=models.Index(fields=["keyword", "-checked_at"], name="idx_positions_kw"),
        ),
        migrations.AddConstraint(
            model_name="keywordposition",
            constraint=models.UniqueConstraint(
                fields=("keyword", "country", "checked_at"),
                name="keyword_positions_keyword_id_country_checked_at_key",
                violation_error_message="Позиция этого ключа для этой страны за эту дату уже есть.",
            ),
        ),
    ]
