"""Анкоры продукта (E3-05, ADR-059): доли типов страниц и стран, доля безанкорного
анкора; в `v_keyword_coverage` — ещё колонки для экрана «Анкоры».

Новые колонки представления — в конце: CREATE OR REPLACE VIEW не даёт менять
порядок прежних.
"""

# Generated by Django 5.2.17 on 2026-10-05 11:42

import django.db.models.deletion
from django.db import migrations, models

import config.db

VIEW = """
CREATE OR REPLACE VIEW v_keyword_coverage AS
SELECT
    k.id,
    k.product_id,
    k.keyword,
    k.tool,
    k.volume,
    k.target_url,
    (SELECT position FROM keyword_positions kp
      WHERE kp.keyword_id = k.id AND kp.country = 'US'
      ORDER BY checked_at DESC LIMIT 1) AS last_position,
    COUNT(pl.id) FILTER (WHERE p.status = 'published') AS links_placed,
    COUNT(pl.id) FILTER (WHERE p.status IN ('planned','ordered','writing','review')) AS links_waiting,
    k.global_volume,
    k.page_type,
    k.anchor_type::text AS anchor_type,
    k.share
FROM keywords k
LEFT JOIN placement_links pl ON pl.keyword_id = k.id
LEFT JOIN placements p ON p.id = pl.placement_id
WHERE k.is_active
GROUP BY k.id;
"""

OLD_VIEW = """
DROP VIEW v_keyword_coverage;
CREATE VIEW v_keyword_coverage AS
SELECT
    k.id,
    k.product_id,
    k.keyword,
    k.tool,
    k.volume,
    k.target_url,
    (SELECT position FROM keyword_positions kp
      WHERE kp.keyword_id = k.id AND kp.country = 'US'
      ORDER BY checked_at DESC LIMIT 1) AS last_position,
    COUNT(pl.id) FILTER (WHERE p.status = 'published') AS links_placed,
    COUNT(pl.id) FILTER (WHERE p.status IN ('planned','ordered','writing','review')) AS links_waiting
FROM keywords k
LEFT JOIN placement_links pl ON pl.keyword_id = k.id
LEFT JOIN placements p ON p.id = pl.placement_id
WHERE k.is_active
GROUP BY k.id;
"""


class Migration(migrations.Migration):
    dependencies = [
        ("keywords", "0003_metric_source_ahrefs_batch"),
        ("sites", "0018_uploads_placements_refdomains"),
    ]

    operations = [
        migrations.CreateModel(
            name="KeywordCoverage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("keyword", models.TextField(verbose_name="анкор")),
                ("tool", models.TextField(null=True, verbose_name="раздел сайта")),
                ("volume", models.IntegerField(null=True, verbose_name="объём")),
                ("target_url", models.TextField(verbose_name="куда ведёт")),
                ("last_position", models.SmallIntegerField(null=True, verbose_name="позиция")),
                ("links_placed", models.BigIntegerField(verbose_name="размещено")),
                ("links_waiting", models.BigIntegerField(verbose_name="ждут")),
                ("global_volume", models.IntegerField(null=True, verbose_name="глобальный объём")),
                ("page_type", models.TextField(null=True, verbose_name="тип страницы")),
                ("anchor_type", models.TextField(null=True, verbose_name="тип анкора")),
                (
                    "share",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, null=True, verbose_name="доля, %"
                    ),
                ),
            ],
            options={
                "verbose_name": "анкор",
                "verbose_name_plural": "анкоры",
                "db_table": "v_keyword_coverage",
                "managed": False,
            },
        ),
        migrations.AddField(
            model_name="keyword",
            name="share",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True, verbose_name="доля, %"
            ),
        ),
        migrations.CreateModel(
            name="CountryShare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "country",
                    models.CharField(blank=True, max_length=2, null=True, verbose_name="страна"),
                ),
                (
                    "target_pct",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="целевая доля, %"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(db_default=config.db.PgNow(), verbose_name="изменено"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="sites.product",
                        verbose_name="продукт",
                    ),
                ),
            ],
            options={
                "verbose_name": "доля страны",
                "verbose_name_plural": "доли стран",
                "db_table": "country_shares",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("product", "country"),
                        name="country_shares_product_id_country_key",
                        nulls_distinct=False,
                        violation_error_message="Эта страна у продукта уже есть.",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PageTypeShare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("page_type", models.TextField(verbose_name="тип страницы")),
                (
                    "target_pct",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="целевая доля, %",
                    ),
                ),
                (
                    "exact_pct",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="прямой, %",
                    ),
                ),
                (
                    "diluted_pct",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="разбавленный, %",
                    ),
                ),
                (
                    "naked_pct",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="безанкор, %",
                    ),
                ),
                (
                    "position",
                    models.SmallIntegerField(db_default=0, default=0, verbose_name="порядок"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(db_default=config.db.PgNow(), verbose_name="изменено"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="sites.product",
                        verbose_name="продукт",
                    ),
                ),
            ],
            options={
                "verbose_name": "доля типа страниц",
                "verbose_name_plural": "доли типов страниц",
                "db_table": "page_type_shares",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("product", "page_type"),
                        name="page_type_shares_product_id_page_type_key",
                        violation_error_message="Такой тип страниц у продукта уже есть.",
                    )
                ],
            },
        ),
        migrations.RunSQL(sql=VIEW, reverse_sql=OLD_VIEW),
    ]
