# Generated by Django 5.2.17 on 2026-09-27 15:16

import django.db.models.deletion
from django.db import migrations, models

import config.db
import config.run_id


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        # Типы-перечисления из schema.sql (ADR-029). Добавлены вручную:
        # makemigrations их не знает. Значения совпадают с TextChoices
        # в apps/observability/models.py — это проверяет tests/test_schema_parity.py.
        migrations.RunSQL(
            sql=[
                "CREATE TYPE check_status AS ENUM ('ok','failed','warning','error')",
                "CREATE TYPE performer AS ENUM ('system','human')",
                "CREATE TYPE llm_status AS ENUM ('ok','error','invalid_json','timeout')",
                "CREATE TYPE task_status AS ENUM ('running','success','failed')",
            ],
            reverse_sql=[
                "DROP TYPE task_status",
                "DROP TYPE llm_status",
                "DROP TYPE performer",
                "DROP TYPE check_status",
            ],
        ),
        migrations.CreateModel(
            name="ApiUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("provider", models.TextField(verbose_name="провайдер")),
                ("endpoint", models.TextField(blank=True, null=True, verbose_name="метод")),
                (
                    "units",
                    models.IntegerField(blank=True, null=True, verbose_name="юнитов или запросов"),
                ),
                (
                    "cost_cents",
                    models.IntegerField(blank=True, null=True, verbose_name="стоимость, центы"),
                ),
                (
                    "currency",
                    models.CharField(
                        db_default="USD", default="USD", max_length=3, verbose_name="валюта"
                    ),
                ),
                (
                    "run_id",
                    models.UUIDField(
                        blank=True,
                        default=config.run_id.current_run_id,
                        null=True,
                        verbose_name="run_id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(db_default=config.db.PgNow(), verbose_name="дата"),
                ),
            ],
            options={
                "verbose_name": "расход API",
                "verbose_name_plural": "расход API",
                "db_table": "api_usage",
                "indexes": [
                    models.Index(fields=["provider", "-created_at"], name="idx_usage_provider")
                ],
            },
        ),
        migrations.CreateModel(
            name="Check",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("entity_type", models.TextField(verbose_name="тип объекта")),
                ("entity_id", models.BigIntegerField(verbose_name="id объекта")),
                ("check_type", models.TextField(verbose_name="тип проверки")),
                (
                    "status",
                    config.db.PgEnumField(
                        choices=[
                            ("ok", "В порядке"),
                            ("failed", "Не пройдена"),
                            ("warning", "Предупреждение"),
                            ("error", "Ошибка проверки"),
                        ],
                        enum_type="check_status",
                        verbose_name="результат",
                    ),
                ),
                ("result", models.JSONField(blank=True, null=True, verbose_name="подробности")),
                (
                    "performed_by",
                    config.db.PgEnumField(
                        choices=[("system", "Система"), ("human", "Человек")],
                        db_default="system",
                        default="system",
                        enum_type="performer",
                        verbose_name="кто проверил",
                    ),
                ),
                (
                    "run_id",
                    models.UUIDField(
                        blank=True,
                        default=config.run_id.current_run_id,
                        null=True,
                        verbose_name="run_id",
                    ),
                ),
                (
                    "checked_at",
                    models.DateTimeField(
                        db_default=config.db.PgNow(), verbose_name="дата проверки"
                    ),
                ),
                (
                    "next_check_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="следующая проверка"),
                ),
            ],
            options={
                "verbose_name": "проверка",
                "verbose_name_plural": "проверки",
                "db_table": "checks",
                "indexes": [
                    models.Index(fields=["entity_type", "entity_id"], name="idx_checks_entity"),
                    models.Index(fields=["check_type", "next_check_at"], name="idx_checks_due"),
                ],
            },
        ),
        migrations.CreateModel(
            name="TaskRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("task_name", models.TextField(verbose_name="задача")),
                (
                    "status",
                    config.db.PgEnumField(
                        choices=[
                            ("running", "Выполняется"),
                            ("success", "Успешно"),
                            ("failed", "Ошибка"),
                        ],
                        enum_type="task_status",
                        verbose_name="состояние",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(db_default=config.db.PgNow(), verbose_name="начало"),
                ),
                ("finished_at", models.DateTimeField(blank=True, null=True, verbose_name="конец")),
                (
                    "duration_ms",
                    models.IntegerField(blank=True, null=True, verbose_name="длительность, мс"),
                ),
                ("error", models.TextField(blank=True, null=True, verbose_name="ошибка")),
                ("payload", models.JSONField(blank=True, null=True, verbose_name="параметры")),
                (
                    "run_id",
                    models.UUIDField(
                        blank=True,
                        default=config.run_id.current_run_id,
                        null=True,
                        verbose_name="run_id",
                    ),
                ),
            ],
            options={
                "verbose_name": "запуск задачи",
                "verbose_name_plural": "запуски задач",
                "db_table": "task_runs",
                "indexes": [
                    models.Index(fields=["task_name", "-started_at"], name="idx_taskruns_name")
                ],
            },
        ),
        migrations.CreateModel(
            name="LlmCall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("task", models.TextField(verbose_name="задача")),
                ("model", models.TextField(verbose_name="модель")),
                (
                    "input_tokens",
                    models.IntegerField(blank=True, null=True, verbose_name="токенов на входе"),
                ),
                (
                    "output_tokens",
                    models.IntegerField(blank=True, null=True, verbose_name="токенов на выходе"),
                ),
                (
                    "cost_cents",
                    models.IntegerField(blank=True, null=True, verbose_name="стоимость, центы"),
                ),
                (
                    "currency",
                    models.CharField(
                        db_default="USD", default="USD", max_length=3, verbose_name="валюта"
                    ),
                ),
                (
                    "duration_ms",
                    models.IntegerField(blank=True, null=True, verbose_name="длительность, мс"),
                ),
                (
                    "status",
                    config.db.PgEnumField(
                        choices=[
                            ("ok", "Успешно"),
                            ("error", "Ошибка"),
                            ("invalid_json", "Невалидный JSON"),
                            ("timeout", "Таймаут"),
                        ],
                        enum_type="llm_status",
                        verbose_name="результат",
                    ),
                ),
                ("response", models.JSONField(blank=True, null=True, verbose_name="ответ")),
                (
                    "entity_type",
                    models.TextField(blank=True, null=True, verbose_name="тип объекта"),
                ),
                (
                    "entity_id",
                    models.BigIntegerField(blank=True, null=True, verbose_name="id объекта"),
                ),
                (
                    "run_id",
                    models.UUIDField(
                        blank=True,
                        default=config.run_id.current_run_id,
                        null=True,
                        verbose_name="run_id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(db_default=config.db.PgNow(), verbose_name="дата"),
                ),
                (
                    "prompt_variant",
                    models.ForeignKey(
                        blank=True,
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="llm_calls",
                        to="content.promptvariant",
                        verbose_name="вариант промпта",
                    ),
                ),
            ],
            options={
                "verbose_name": "вызов LLM",
                "verbose_name_plural": "вызовы LLM",
                "db_table": "llm_calls",
                "indexes": [
                    models.Index(fields=["task", "-created_at"], name="idx_llm_task"),
                    models.Index(fields=["run_id"], name="idx_llm_run"),
                ],
            },
        ),
        # Представление — текстом из schema.sql (ADR-029). Срок берётся из
        # последней проверки: минимум по всей истории давал вечные
        # «просрочки» по уже выполненным проверкам.
        migrations.RunSQL(
            sql="""
                CREATE VIEW v_overdue_checks AS
                SELECT *
                FROM (
                    SELECT DISTINCT ON (entity_type, entity_id, check_type)
                           entity_type, entity_id, check_type, status,
                           checked_at AS last_checked, next_check_at AS due_at
                    FROM checks
                    ORDER BY entity_type, entity_id, check_type, checked_at DESC
                ) latest
                WHERE due_at < now();
            """,
            reverse_sql="DROP VIEW v_overdue_checks",
        ),
    ]
