# Generated by Django 5.2.17 on 2026-09-27 14:48

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models

import config.db


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        # Типы-перечисления из schema.sql (ADR-029). Добавлены вручную:
        # makemigrations их не знает. Значения совпадают с TextChoices
        # в apps/sites/models.py — это проверяет tests/test_schema_parity.py.
        # metric_source нужен и блоку 2 (keyword_positions): его миграции
        # зависят от этой.
        migrations.RunSQL(
            sql=[
                "CREATE TYPE site_status AS ENUM"
                " ('new','auditing','approved','rejected','placed','blacklisted')",
                "CREATE TYPE metric_source AS ENUM"
                " ('ahrefs_api','serp_api','manual','csv_import','collaborator_api')",
                "CREATE TYPE audit_verdict AS ENUM ('yes','no','borderline')",
                "CREATE TYPE audit_author AS ENUM ('human','llm','system')",
            ],
            reverse_sql=[
                "DROP TYPE audit_author",
                "DROP TYPE audit_verdict",
                "DROP TYPE metric_source",
                "DROP TYPE site_status",
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.TextField(verbose_name="название")),
                ("domain", models.TextField(verbose_name="домен")),
                (
                    "is_active",
                    models.BooleanField(db_default=True, default=True, verbose_name="активен"),
                ),
                (
                    "created_at",
                    models.DateTimeField(db_default=config.db.PgNow(), verbose_name="создан"),
                ),
            ],
            options={
                "verbose_name": "продукт",
                "verbose_name_plural": "продукты",
                "db_table": "products",
                "constraints": [
                    models.UniqueConstraint(fields=("domain",), name="products_domain_key")
                ],
            },
        ),
        migrations.CreateModel(
            name="Site",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("domain", models.TextField(verbose_name="домен")),
                (
                    "collaborator_url",
                    models.TextField(
                        blank=True, null=True, verbose_name="карточка на Collaborator"
                    ),
                ),
                ("source", models.TextField(blank=True, null=True, verbose_name="источник")),
                ("language", models.TextField(blank=True, null=True, verbose_name="основной язык")),
                (
                    "languages",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(),
                        blank=True,
                        null=True,
                        size=None,
                        verbose_name="языки",
                    ),
                ),
                (
                    "topics",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(),
                        blank=True,
                        null=True,
                        size=None,
                        verbose_name="тематики",
                    ),
                ),
                (
                    "declared_topics",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(),
                        blank=True,
                        null=True,
                        size=None,
                        verbose_name="особые тематики",
                    ),
                ),
                ("site_type", models.TextField(blank=True, null=True, verbose_name="тип сайта")),
                (
                    "links_allowed",
                    models.SmallIntegerField(
                        blank=True, null=True, verbose_name="ссылок разрешено"
                    ),
                ),
                ("link_type", models.TextField(blank=True, null=True, verbose_name="тип ссылки")),
                (
                    "marks_as_ad",
                    models.BooleanField(blank=True, null=True, verbose_name="пометка «реклама»"),
                ),
                ("notes", models.TextField(blank=True, null=True, verbose_name="заметки")),
                (
                    "content_selector",
                    models.TextField(blank=True, null=True, verbose_name="CSS-селектор статьи"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(db_default=False, default=False, verbose_name="удалена"),
                ),
                (
                    "created_at",
                    models.DateTimeField(db_default=config.db.PgNow(), verbose_name="создана"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_default=config.db.PgNow(), verbose_name="изменена"
                    ),
                ),
            ],
            options={
                "verbose_name": "площадка",
                "verbose_name_plural": "площадки",
                "db_table": "sites",
                "constraints": [
                    models.UniqueConstraint(fields=("domain",), name="sites_domain_key")
                ],
            },
        ),
        migrations.CreateModel(
            name="ProductSite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    config.db.PgEnumField(
                        choices=[
                            ("new", "Новая"),
                            ("auditing", "На аудите"),
                            ("approved", "Одобрена"),
                            ("rejected", "Отклонена"),
                            ("placed", "Размещались"),
                            ("blacklisted", "Чёрный список"),
                        ],
                        db_default="new",
                        default="new",
                        enum_type="site_status",
                        verbose_name="статус",
                    ),
                ),
                (
                    "reject_reason",
                    models.TextField(blank=True, null=True, verbose_name="причина отказа"),
                ),
                (
                    "content_profile",
                    models.JSONField(blank=True, null=True, verbose_name="соответствие тематике"),
                ),
                (
                    "imported_undecided",
                    models.BooleanField(
                        db_default=False, default=False, verbose_name="импортирована без решения"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(db_default=config.db.PgNow(), verbose_name="создана"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_default=config.db.PgNow(), verbose_name="изменена"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="product_sites",
                        to="sites.product",
                        verbose_name="продукт",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="product_sites",
                        to="sites.site",
                        verbose_name="площадка",
                    ),
                ),
            ],
            options={
                "verbose_name": "площадка продукта",
                "verbose_name_plural": "площадки продуктов",
                "db_table": "product_sites",
                "indexes": [
                    models.Index(fields=["product", "status"], name="idx_product_sites_status")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("site", "product"), name="product_sites_site_id_product_id_key"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="GrayScan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "total_indexed",
                    models.IntegerField(blank=True, null=True, verbose_name="страниц в индексе"),
                ),
                (
                    "gray_hits",
                    models.IntegerField(blank=True, null=True, verbose_name="серых страниц"),
                ),
                (
                    "ratio",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="доля серых, %",
                    ),
                ),
                (
                    "breakdown",
                    models.JSONField(blank=True, null=True, verbose_name="по категориям"),
                ),
                (
                    "sample_urls",
                    models.JSONField(blank=True, null=True, verbose_name="примеры адресов"),
                ),
                (
                    "method",
                    config.db.PgEnumField(
                        choices=[
                            ("ahrefs_api", "Ahrefs API"),
                            ("serp_api", "SERP API"),
                            ("manual", "Вручную"),
                            ("csv_import", "Импорт из файла"),
                            ("collaborator_api", "Collaborator API"),
                        ],
                        db_default="serp_api",
                        default="serp_api",
                        enum_type="metric_source",
                        verbose_name="способ",
                    ),
                ),
                (
                    "checked_at",
                    models.DateTimeField(db_default=config.db.PgNow(), verbose_name="дата замера"),
                ),
                (
                    "site",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="gray_scans",
                        to="sites.site",
                        verbose_name="площадка",
                    ),
                ),
            ],
            options={
                "verbose_name": "проверка серости",
                "verbose_name_plural": "проверки серости",
                "db_table": "gray_scans",
                "indexes": [models.Index(fields=["site", "-checked_at"], name="idx_gray_site")],
            },
        ),
        migrations.CreateModel(
            name="SiteAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "verdict",
                    config.db.PgEnumField(
                        choices=[("yes", "Да"), ("no", "Нет"), ("borderline", "Пограничная")],
                        enum_type="audit_verdict",
                        verbose_name="вердикт",
                    ),
                ),
                ("score", models.SmallIntegerField(blank=True, null=True, verbose_name="оценка")),
                ("blockers", models.JSONField(blank=True, null=True, verbose_name="стоп-факторы")),
                (
                    "strengths",
                    models.JSONField(blank=True, null=True, verbose_name="сильные стороны"),
                ),
                (
                    "weaknesses",
                    models.JSONField(blank=True, null=True, verbose_name="слабые стороны"),
                ),
                ("summary", models.TextField(blank=True, null=True, verbose_name="вывод")),
                (
                    "missing_data",
                    models.JSONField(blank=True, null=True, verbose_name="не хватило данных"),
                ),
                (
                    "price_flag",
                    models.JSONField(blank=True, null=True, verbose_name="превышение ориентира"),
                ),
                ("dossier", models.JSONField(blank=True, null=True, verbose_name="досье")),
                (
                    "author",
                    config.db.PgEnumField(
                        choices=[("human", "Человек"), ("llm", "LLM"), ("system", "Система")],
                        enum_type="audit_author",
                        verbose_name="автор",
                    ),
                ),
                ("model", models.TextField(blank=True, null=True, verbose_name="модель")),
                ("run_id", models.UUIDField(blank=True, null=True, verbose_name="run_id")),
                (
                    "created_at",
                    models.DateTimeField(db_default=config.db.PgNow(), verbose_name="дата"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audits",
                        to="sites.product",
                        verbose_name="продукт",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audits",
                        to="sites.site",
                        verbose_name="площадка",
                    ),
                ),
            ],
            options={
                "verbose_name": "аудит",
                "verbose_name_plural": "аудиты",
                "db_table": "site_audits",
                "indexes": [
                    models.Index(fields=["site", "product", "-created_at"], name="idx_audits_site")
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("score__gte", 0), ("score__lte", 100)),
                        name="site_audits_score_check",
                        violation_error_message="Оценка — от 0 до 100.",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SiteMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("dr", models.SmallIntegerField(blank=True, null=True, verbose_name="DR")),
                (
                    "organic_traffic",
                    models.IntegerField(blank=True, null=True, verbose_name="органический трафик"),
                ),
                (
                    "us_traffic",
                    models.IntegerField(blank=True, null=True, verbose_name="трафик США"),
                ),
                ("top_geo", models.TextField(blank=True, null=True, verbose_name="основное гео")),
                (
                    "top_geo_traffic",
                    models.IntegerField(blank=True, null=True, verbose_name="трафик основного гео"),
                ),
                (
                    "total_keywords",
                    models.IntegerField(blank=True, null=True, verbose_name="ключей в органике"),
                ),
                (
                    "source",
                    config.db.PgEnumField(
                        choices=[
                            ("ahrefs_api", "Ahrefs API"),
                            ("serp_api", "SERP API"),
                            ("manual", "Вручную"),
                            ("csv_import", "Импорт из файла"),
                            ("collaborator_api", "Collaborator API"),
                        ],
                        db_default="manual",
                        default="manual",
                        enum_type="metric_source",
                        verbose_name="источник",
                    ),
                ),
                ("raw", models.JSONField(blank=True, null=True, verbose_name="сырой ответ")),
                (
                    "checked_at",
                    models.DateTimeField(db_default=config.db.PgNow(), verbose_name="дата замера"),
                ),
                (
                    "site",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="metrics",
                        to="sites.site",
                        verbose_name="площадка",
                    ),
                ),
            ],
            options={
                "verbose_name": "метрики",
                "verbose_name_plural": "метрики",
                "db_table": "site_metrics",
                "indexes": [models.Index(fields=["site", "-checked_at"], name="idx_metrics_site")],
            },
        ),
        migrations.CreateModel(
            name="SitePrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "placement_cents",
                    models.IntegerField(blank=True, null=True, verbose_name="размещение, центы"),
                ),
                (
                    "announce_cents",
                    models.IntegerField(blank=True, null=True, verbose_name="анонс, центы"),
                ),
                (
                    "writing_cents",
                    models.IntegerField(blank=True, null=True, verbose_name="написание, центы"),
                ),
                (
                    "currency",
                    models.CharField(
                        db_default="EUR", default="EUR", max_length=3, verbose_name="валюта"
                    ),
                ),
                (
                    "source",
                    config.db.PgEnumField(
                        choices=[
                            ("ahrefs_api", "Ahrefs API"),
                            ("serp_api", "SERP API"),
                            ("manual", "Вручную"),
                            ("csv_import", "Импорт из файла"),
                            ("collaborator_api", "Collaborator API"),
                        ],
                        db_default="manual",
                        default="manual",
                        enum_type="metric_source",
                        verbose_name="источник",
                    ),
                ),
                (
                    "checked_at",
                    models.DateTimeField(db_default=config.db.PgNow(), verbose_name="дата замера"),
                ),
                (
                    "site",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="prices",
                        to="sites.site",
                        verbose_name="площадка",
                    ),
                ),
            ],
            options={
                "verbose_name": "цены",
                "verbose_name_plural": "цены",
                "db_table": "site_prices",
                "indexes": [models.Index(fields=["site", "-checked_at"], name="idx_prices_site")],
            },
        ),
    ]
