# Generated by Django 5.2.17 on 2026-09-27 19:12

import django.db.models.deletion
from django.db import migrations, models

import config.db


class Migration(migrations.Migration):
    dependencies = [
        ("sites", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.TextField(verbose_name="название")),
                ("source", models.TextField(blank=True, null=True, verbose_name="откуда")),
                (
                    "created_at",
                    models.DateTimeField(db_default=config.db.PgNow(), verbose_name="создан"),
                ),
            ],
            options={
                "verbose_name": "список площадок",
                "verbose_name_plural": "списки площадок",
                "db_table": "site_lists",
                "constraints": [
                    models.UniqueConstraint(fields=("name",), name="site_lists_name_key")
                ],
            },
        ),
        migrations.CreateModel(
            name="SiteListItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "first_seen",
                    models.BooleanField(
                        db_default=False, default=False, verbose_name="впервые в базе"
                    ),
                ),
                (
                    "added_at",
                    models.DateTimeField(db_default=config.db.PgNow(), verbose_name="добавлена"),
                ),
                (
                    "site",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="list_items",
                        to="sites.site",
                        verbose_name="площадка",
                    ),
                ),
                (
                    "site_list",
                    models.ForeignKey(
                        db_column="list_id",
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="sites.sitelist",
                        verbose_name="список",
                    ),
                ),
            ],
            options={
                "verbose_name": "площадка в списке",
                "verbose_name_plural": "площадки в списке",
                "db_table": "site_list_items",
                "indexes": [models.Index(fields=["site"], name="idx_list_items_site")],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("site_list", "site"), name="site_list_items_list_id_site_id_key"
                    )
                ],
            },
        ),
    ]
