# Generated by Django 5.2.17 on 2026-09-28 17:04

import django.contrib.postgres.fields
from django.db import migrations, models

import config.db


class Migration(migrations.Migration):
    dependencies = [
        ("sites", "0003_views"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductSiteLatest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    config.db.PgEnumField(
                        choices=[
                            ("new", "Новая"),
                            ("auditing", "На аудите"),
                            ("approved", "Одобрена"),
                            ("rejected", "Отклонена"),
                            ("placed", "Размещались"),
                            ("blacklisted", "Чёрный список"),
                        ],
                        enum_type="site_status",
                        verbose_name="статус",
                    ),
                ),
                ("reject_reason", models.TextField(null=True, verbose_name="причина отказа")),
                (
                    "imported_undecided",
                    models.BooleanField(verbose_name="импортирована без решения"),
                ),
                ("domain", models.TextField(verbose_name="домен")),
                ("language", models.TextField(null=True, verbose_name="язык")),
                (
                    "topics",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), null=True, size=None, verbose_name="тематики"
                    ),
                ),
                (
                    "declared_topics",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(),
                        null=True,
                        size=None,
                        verbose_name="особые тематики",
                    ),
                ),
                (
                    "links_allowed",
                    models.SmallIntegerField(null=True, verbose_name="ссылок разрешено"),
                ),
                ("link_type", models.TextField(null=True, verbose_name="тип ссылки")),
                ("marks_as_ad", models.BooleanField(null=True, verbose_name="пометка «реклама»")),
                ("dr", models.SmallIntegerField(null=True, verbose_name="DR")),
                ("organic_traffic", models.IntegerField(null=True, verbose_name="трафик")),
                (
                    "total_keywords",
                    models.IntegerField(null=True, verbose_name="ключей в органике"),
                ),
                ("top_geo", models.TextField(null=True, verbose_name="основное гео")),
                ("metrics_at", models.DateTimeField(null=True, verbose_name="дата метрик")),
                (
                    "placement_cents",
                    models.IntegerField(null=True, verbose_name="размещение, центы"),
                ),
                ("announce_cents", models.IntegerField(null=True, verbose_name="анонс, центы")),
                ("writing_cents", models.IntegerField(null=True, verbose_name="написание, центы")),
                ("prices_at", models.DateTimeField(null=True, verbose_name="дата цен")),
                ("reference_total_cents", models.IntegerField(verbose_name="к ориентиру, центы")),
                ("we_write", models.BooleanField(null=True, verbose_name="пишем мы")),
                (
                    "expected_spend_cents",
                    models.IntegerField(null=True, verbose_name="плановые расходы, центы"),
                ),
                (
                    "gray_ratio",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, null=True, verbose_name="доля серых, %"
                    ),
                ),
                (
                    "last_verdict",
                    config.db.PgEnumField(
                        choices=[("yes", "Да"), ("no", "Нет"), ("borderline", "Пограничная")],
                        enum_type="audit_verdict",
                        null=True,
                        verbose_name="вердикт",
                    ),
                ),
                ("last_score", models.SmallIntegerField(null=True, verbose_name="оценка")),
                ("audited_at", models.DateTimeField(null=True, verbose_name="дата аудита")),
                ("placements_published", models.BigIntegerField(verbose_name="опубликовано")),
                (
                    "other_products_placed",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(),
                        null=True,
                        size=None,
                        verbose_name="размещались другие продукты",
                    ),
                ),
            ],
            options={
                "verbose_name": "площадка продукта на сегодня",
                "verbose_name_plural": "площадки продукта",
                "db_table": "v_product_site_latest",
                "managed": False,
            },
        ),
    ]
