# Generated by Django 5.2.17 on 2026-09-28 20:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sites", "0004_product_site_latest"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productsite",
            options={
                "verbose_name": "решение по площадке",
                "verbose_name_plural": "решения по площадкам",
            },
        ),
        migrations.AlterModelOptions(
            name="productsitelatest",
            options={
                "managed": False,
                "verbose_name": "площадка продукта на сегодня",
                "verbose_name_plural": "площадки",
            },
        ),
        migrations.AlterModelOptions(
            name="site",
            options={"verbose_name": "площадка", "verbose_name_plural": "каталог площадок"},
        ),
        migrations.AlterModelOptions(
            name="sitelist",
            options={"verbose_name": "рабочий список", "verbose_name_plural": "рабочие списки"},
        ),
        migrations.AlterModelOptions(
            name="sitelistitem",
            options={
                "verbose_name": "строка рабочего списка",
                "verbose_name_plural": "строки рабочих списков",
            },
        ),
    ]
