# Generated by Django 5.2.17 on 2026-10-01 15:06

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models

import config.db


class Migration(migrations.Migration):
    dependencies = [
        ("sites", "0005_verbose_names_menu"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExchangeRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("currency", models.CharField(max_length=3, verbose_name="валюта")),
                ("rate_date", models.DateField(verbose_name="дата курса")),
                (
                    "rate",
                    models.DecimalField(decimal_places=6, max_digits=14, verbose_name="за 1 евро"),
                ),
                (
                    "created_at",
                    models.DateTimeField(db_default=config.db.PgNow(), verbose_name="получен"),
                ),
            ],
            options={
                "verbose_name": "курс валюты",
                "verbose_name_plural": "курсы валют",
                "db_table": "exchange_rates",
            },
        ),
        migrations.CreateModel(
            name="Seller",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.TextField(verbose_name="имя")),
                ("contacts", models.TextField(blank=True, null=True, verbose_name="контакты")),
                ("notes", models.TextField(blank=True, null=True, verbose_name="заметки")),
                (
                    "currency",
                    models.CharField(
                        db_default="EUR", default="EUR", max_length=3, verbose_name="валюта прайсов"
                    ),
                ),
                (
                    "is_collaborator",
                    models.BooleanField(
                        db_default=False, default=False, verbose_name="каталог Collaborator"
                    ),
                ),
                (
                    "metrics_trusted",
                    models.BooleanField(
                        db_default=False,
                        default=False,
                        help_text="DR и трафик этого продавца показываются как наши замеры и идут в графики.",
                        verbose_name="метрикам доверяем",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(db_default=config.db.PgNow(), verbose_name="заведён"),
                ),
            ],
            options={
                "verbose_name": "продавец",
                "verbose_name_plural": "продавцы",
                "db_table": "sellers",
            },
        ),
        migrations.CreateModel(
            name="SiteNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("body", models.TextField(verbose_name="заметка")),
                ("source", models.TextField(blank=True, null=True, verbose_name="источник")),
                (
                    "created_at",
                    models.DateTimeField(db_default=config.db.PgNow(), verbose_name="дата"),
                ),
            ],
            options={
                "verbose_name": "заметка",
                "verbose_name_plural": "заметки",
                "db_table": "site_notes",
            },
        ),
        migrations.AlterModelOptions(
            name="siteprice",
            options={
                "verbose_name": "предложение продавца",
                "verbose_name_plural": "предложения продавцов",
            },
        ),
        migrations.RemoveIndex(
            model_name="siteprice",
            name="idx_prices_site",
        ),
        migrations.AddField(
            model_name="site",
            name="price",
            field=models.ForeignKey(
                blank=True,
                db_index=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="sites.siteprice",
                verbose_name="рабочая цена",
            ),
        ),
        migrations.AddField(
            model_name="siteprice",
            name="extra",
            field=models.JSONField(blank=True, null=True, verbose_name="прочие данные"),
        ),
        migrations.AddField(
            model_name="siteprice",
            name="gray_cents",
            field=models.IntegerField(blank=True, null=True, verbose_name="серая цена, центы"),
        ),
        migrations.AddField(
            model_name="siteprice",
            name="placement_type",
            field=config.db.PgEnumField(
                choices=[("guest_post", "публикация"), ("link_insertion", "вставка ссылки")],
                db_default="guest_post",
                default="guest_post",
                enum_type="placement_type",
                verbose_name="услуга",
            ),
        ),
        migrations.AddField(
            model_name="siteprice",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="разобрано"),
        ),
        migrations.AlterField(
            model_name="siteprice",
            name="checked_at",
            field=models.DateTimeField(db_default=config.db.PgNow(), verbose_name="дата цены"),
        ),
        migrations.AlterField(
            model_name="siteprice",
            name="placement_cents",
            field=models.IntegerField(blank=True, null=True, verbose_name="цена услуги, центы"),
        ),
        migrations.AddConstraint(
            model_name="exchangerate",
            constraint=models.UniqueConstraint(
                fields=("currency", "rate_date"), name="exchange_rates_currency_rate_date_key"
            ),
        ),
        migrations.AddConstraint(
            model_name="seller",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                name="sellers_name_key",
                violation_error_message="Продавец с таким именем уже есть (регистр не важен).",
            ),
        ),
        migrations.AddConstraint(
            model_name="seller",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_collaborator", True)),
                fields=("is_collaborator",),
                name="sellers_collaborator_key",
                violation_error_message="Каталог Collaborator уже заведён.",
            ),
        ),
        migrations.AddField(
            model_name="sitemetric",
            name="seller",
            field=models.ForeignKey(
                blank=True,
                db_index=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="metrics",
                to="sites.seller",
                verbose_name="со слов продавца",
            ),
        ),
        migrations.AddField(
            model_name="siteprice",
            name="seller",
            field=models.ForeignKey(
                db_index=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="prices",
                to="sites.seller",
                verbose_name="продавец",
            ),
        ),
        migrations.AddIndex(
            model_name="siteprice",
            index=models.Index(
                fields=["site", "seller", "placement_type", "-checked_at"], name="idx_prices_site"
            ),
        ),
        migrations.AddIndex(
            model_name="siteprice",
            index=models.Index(
                condition=models.Q(("reviewed_at__isnull", True)),
                fields=["site"],
                name="idx_prices_pending",
            ),
        ),
        migrations.AddField(
            model_name="sitenote",
            name="author",
            field=models.ForeignKey(
                blank=True,
                db_index=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="site_notes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="автор",
            ),
        ),
        migrations.AddField(
            model_name="sitenote",
            name="product",
            field=models.ForeignKey(
                blank=True,
                db_index=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="site_notes",
                to="sites.product",
                verbose_name="продукт",
            ),
        ),
        migrations.AddField(
            model_name="sitenote",
            name="site",
            field=models.ForeignKey(
                db_index=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="history_notes",
                to="sites.site",
                verbose_name="площадка",
            ),
        ),
        migrations.AddIndex(
            model_name="sitenote",
            index=models.Index(fields=["site", "-created_at"], name="idx_site_notes_site"),
        ),
    ]
