# Generated by Django 5.2.17 on 2026-10-01 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sites", "0007_offers_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="site",
            name="notes",
        ),
        migrations.AlterField(
            model_name="sitenote",
            name="site",
            field=models.ForeignKey(
                db_index=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="notes",
                to="sites.site",
                verbose_name="площадка",
            ),
        ),
        migrations.AlterField(
            model_name="siteprice",
            name="seller",
            field=models.ForeignKey(
                db_index=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="prices",
                to="sites.seller",
                verbose_name="продавец",
            ),
        ),
    ]
