# Generated by Django 5.2.17 on 2026-10-01 15:11

from django.db import migrations, models

import config.db


class Migration(migrations.Migration):
    dependencies = [
        ("sites", "0009_views_working_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("seller_name", models.TextField(db_column="seller", verbose_name="продавец")),
                (
                    "placement_type",
                    config.db.PgEnumField(
                        choices=[
                            ("guest_post", "публикация"),
                            ("link_insertion", "вставка ссылки"),
                        ],
                        enum_type="placement_type",
                        verbose_name="услуга",
                    ),
                ),
                (
                    "placement_cents",
                    models.IntegerField(null=True, verbose_name="цена услуги, центы"),
                ),
                ("currency", models.CharField(max_length=3, verbose_name="валюта")),
                (
                    "placement_eur_cents",
                    models.IntegerField(null=True, verbose_name="цена услуги, евроценты"),
                ),
                ("announce_cents", models.IntegerField(null=True, verbose_name="анонс, центы")),
                ("writing_cents", models.IntegerField(null=True, verbose_name="написание, центы")),
                ("gray_cents", models.IntegerField(null=True, verbose_name="серая цена, центы")),
                ("extra", models.JSONField(null=True, verbose_name="прочие данные")),
                ("reviewed_at", models.DateTimeField(null=True, verbose_name="разобрано")),
                ("checked_at", models.DateTimeField(verbose_name="дата цены")),
            ],
            options={
                "verbose_name": "текущее предложение",
                "verbose_name_plural": "текущие предложения",
                "db_table": "v_site_offers",
                "managed": False,
            },
        ),
    ]
