# Generated by Django 5.2.17 on 2026-10-01 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import config.db


class Migration(migrations.Migration):
    dependencies = [
        ("sites", "0010_site_offers"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Типы-перечисления из schema.sql 1.8 (ADR-029, ADR-044): makemigrations
        # их не знает. Значения совпадают с TextChoices в apps/sites/models.py —
        # это проверяет tests/test_schema_parity.py.
        migrations.RunSQL(
            sql=[
                "CREATE TYPE upload_kind AS ENUM ('price_list','collaborator_catalog')",
                "CREATE TYPE upload_status AS ENUM"
                " ('new','checking','checked','writing','done','failed')",
                "CREATE TYPE review_group AS ENUM"
                " ('cheaper','changed','new','rejected','pricier','other_service','same')",
            ],
            reverse_sql=[
                "DROP TYPE review_group",
                "DROP TYPE upload_status",
                "DROP TYPE upload_kind",
            ],
        ),
        migrations.AddField(
            model_name="seller",
            name="column_map",
            field=models.JSONField(blank=True, null=True, verbose_name="разметка колонок"),
        ),
        migrations.CreateModel(
            name="Upload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "kind",
                    config.db.PgEnumField(
                        choices=[
                            ("price_list", "Прайс продавца"),
                            ("collaborator_catalog", "Каталог Collaborator"),
                        ],
                        enum_type="upload_kind",
                        verbose_name="что загружаем",
                    ),
                ),
                ("prices_date", models.DateField(verbose_name="дата цен")),
                ("file_name", models.TextField(verbose_name="файл")),
                ("file_path", models.TextField(verbose_name="путь к файлу")),
                ("file_sha256", models.CharField(max_length=64, verbose_name="отпечаток файла")),
                (
                    "header_row",
                    models.IntegerField(blank=True, null=True, verbose_name="строка заголовков"),
                ),
                ("columns", models.JSONField(blank=True, null=True, verbose_name="колонки файла")),
                ("mapping", models.JSONField(blank=True, null=True, verbose_name="разметка")),
                (
                    "currency",
                    models.CharField(
                        blank=True, max_length=3, null=True, verbose_name="валюта цен"
                    ),
                ),
                (
                    "status",
                    config.db.PgEnumField(
                        choices=[
                            ("new", "Разметка колонок"),
                            ("checking", "Проверяется"),
                            ("checked", "Проверен, ждёт записи"),
                            ("writing", "Записывается"),
                            ("done", "Записан"),
                            ("failed", "Ошибка"),
                        ],
                        db_default="new",
                        default="new",
                        enum_type="upload_status",
                        verbose_name="состояние",
                    ),
                ),
                (
                    "summary",
                    models.JSONField(blank=True, null=True, verbose_name="сводка до записи"),
                ),
                ("result", models.JSONField(blank=True, null=True, verbose_name="итог записи")),
                ("error", models.TextField(blank=True, null=True, verbose_name="ошибка")),
                ("run_id", models.UUIDField(blank=True, null=True, verbose_name="run_id")),
                (
                    "created_at",
                    models.DateTimeField(db_default=config.db.PgNow(), verbose_name="загружен"),
                ),
                ("written_at", models.DateTimeField(blank=True, null=True, verbose_name="записан")),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="uploads",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="загрузил",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="uploads",
                        to="sites.seller",
                        verbose_name="продавец",
                    ),
                ),
                (
                    "site_list",
                    models.ForeignKey(
                        blank=True,
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="uploads",
                        to="sites.sitelist",
                        verbose_name="рабочий список",
                    ),
                ),
            ],
            options={
                "verbose_name": "загрузка",
                "verbose_name_plural": "загрузки",
                "db_table": "uploads",
            },
        ),
        migrations.CreateModel(
            name="UploadItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "review_group",
                    config.db.PgEnumField(
                        choices=[
                            ("cheaper", "Дешевле рабочей"),
                            ("changed", "Цена изменилась"),
                            ("new", "Новые"),
                            ("rejected", "Отклоняли"),
                            ("pricier", "Дороже рабочей"),
                            ("other_service", "Другая услуга"),
                            ("same", "Без изменений"),
                        ],
                        enum_type="review_group",
                        verbose_name="вкладка",
                    ),
                ),
                (
                    "needs_decision",
                    models.BooleanField(
                        db_default=False, default=False, verbose_name="ждало решения"
                    ),
                ),
                (
                    "auto_applied",
                    models.BooleanField(
                        db_default=False, default=False, verbose_name="стало рабочей само"
                    ),
                ),
                (
                    "site_created",
                    models.BooleanField(
                        db_default=False, default=False, verbose_name="новая в базе"
                    ),
                ),
                ("line", models.IntegerField(blank=True, null=True, verbose_name="строка файла")),
                (
                    "source_value",
                    models.TextField(blank=True, null=True, verbose_name="адрес в файле"),
                ),
                (
                    "price",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="sites.siteprice",
                        verbose_name="предложение из файла",
                    ),
                ),
                (
                    "ref_price",
                    models.ForeignKey(
                        blank=True,
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="sites.siteprice",
                        verbose_name="рабочая цена до загрузки",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="sites.site",
                        verbose_name="площадка",
                    ),
                ),
                (
                    "upload",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="sites.upload",
                        verbose_name="загрузка",
                    ),
                ),
            ],
            options={
                "verbose_name": "строка разбора",
                "verbose_name_plural": "строки разбора",
                "db_table": "upload_items",
                "indexes": [
                    models.Index(fields=["upload", "review_group"], name="idx_upload_items_upload")
                ],
            },
        ),
    ]
