# Generated by Django 5.2.17 on 2026-10-03 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import config.db


class Migration(migrations.Migration):
    dependencies = [
        ("placements", "0004_seller_employee"),
        ("sites", "0015_site_statuses"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Тип-перечисление из schema.sql 1.11 (ADR-029, ADR-049): makemigrations его
        # не знает. Значения — StatusSource, сверяет tests/test_schema_parity.py.
        migrations.RunSQL(
            sql="CREATE TYPE status_source AS ENUM"
            " ('panel','form','placement','import','upload','migration')",
            reverse_sql="DROP TYPE status_source",
        ),
        migrations.CreateModel(
            name="SiteStatusChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "from_status",
                    config.db.PgEnumField(
                        blank=True,
                        choices=[
                            ("new", "Новая"),
                            ("viewed", "Просмотрено"),
                            ("approved", "Одобрена"),
                            ("ordered", "Заявка отправлена"),
                            ("placed", "Размещались"),
                            ("discarded", "Отбрасываю"),
                            ("declined", "Отказала площадка"),
                            ("blacklisted", "Чёрный список"),
                            ("auditing", "На аудите"),
                        ],
                        enum_type="site_status",
                        null=True,
                        verbose_name="был",
                    ),
                ),
                (
                    "to_status",
                    config.db.PgEnumField(
                        choices=[
                            ("new", "Новая"),
                            ("viewed", "Просмотрено"),
                            ("approved", "Одобрена"),
                            ("ordered", "Заявка отправлена"),
                            ("placed", "Размещались"),
                            ("discarded", "Отбрасываю"),
                            ("declined", "Отказала площадка"),
                            ("blacklisted", "Чёрный список"),
                            ("auditing", "На аудите"),
                        ],
                        enum_type="site_status",
                        verbose_name="стал",
                    ),
                ),
                (
                    "source",
                    config.db.PgEnumField(
                        blank=True,
                        choices=[
                            ("panel", "панель"),
                            ("form", "форма"),
                            ("placement", "по размещению"),
                            ("import", "импорт таблицы"),
                            ("upload", "загрузка"),
                            ("migration", "миграция"),
                        ],
                        enum_type="status_source",
                        null=True,
                        verbose_name="откуда",
                    ),
                ),
                ("run_id", models.UUIDField(blank=True, null=True, verbose_name="run_id")),
                (
                    "changed_at",
                    models.DateTimeField(db_default=config.db.PgNow(), verbose_name="когда"),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="кто",
                    ),
                ),
                (
                    "placement",
                    models.ForeignKey(
                        blank=True,
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="placements.placement",
                        verbose_name="по размещению",
                    ),
                ),
                (
                    "product_site",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="status_changes",
                        to="sites.productsite",
                        verbose_name="площадка у продукта",
                    ),
                ),
            ],
            options={
                "verbose_name": "смена статуса площадки",
                "verbose_name_plural": "история статусов площадок",
                "db_table": "site_status_changes",
                "indexes": [
                    models.Index(
                        fields=["product_site", "-changed_at"], name="idx_site_status_changes"
                    )
                ],
            },
        ),
        # Триггер пишет строку истории при каждой смене статуса (ADR-049); текст —
        # как в schema.sql, сверяет tests/test_schema_parity.py.
        migrations.RunSQL(
            sql=[
                """
CREATE FUNCTION log_site_status_change() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    INSERT INTO site_status_changes
        (product_site_id, from_status, to_status, source, actor_id, placement_id, run_id)
    VALUES (
        NEW.id,
        CASE WHEN TG_OP = 'UPDATE' THEN OLD.status END,
        NEW.status,
        NULLIF(current_setting('seo.change_source', true), '')::status_source,
        NULLIF(current_setting('seo.change_actor', true), '')::integer,
        NULLIF(current_setting('seo.change_placement', true), '')::bigint,
        NULLIF(current_setting('seo.change_run_id', true), '')::uuid
    );
    RETURN NULL;
END
$$
""",
                "CREATE TRIGGER product_sites_status_insert AFTER INSERT ON product_sites"
                " FOR EACH ROW WHEN (NEW.status <> 'new') EXECUTE FUNCTION log_site_status_change()",
                "CREATE TRIGGER product_sites_status_update AFTER UPDATE OF status ON product_sites"
                " FOR EACH ROW WHEN (OLD.status IS DISTINCT FROM NEW.status)"
                " EXECUTE FUNCTION log_site_status_change()",
            ],
            reverse_sql=[
                "DROP TRIGGER product_sites_status_update ON product_sites",
                "DROP TRIGGER product_sites_status_insert ON product_sites",
                "DROP FUNCTION log_site_status_change()",
            ],
        ),
    ]
