# Generated by Django 5.2.17 on 2026-10-05 11:43

from django.conf import settings
from django.db import migrations, models

import config.db


class Migration(migrations.Migration):
    dependencies = [
        ("sites", "0019_upload_kind_anchors"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="upload",
            name="uploads_seller_check",
        ),
        migrations.AlterField(
            model_name="upload",
            name="kind",
            field=config.db.PgEnumField(
                choices=[
                    ("price_list", "Прайс продавца"),
                    ("collaborator_catalog", "Каталог Collaborator"),
                    ("ahrefs_batch", "Ahrefs Batch Analysis"),
                    ("placements", "Размещения продукта"),
                    ("ahrefs_refdomains", "Ссылающиеся домены Ahrefs"),
                    ("anchors", "Анкоры продукта"),
                ],
                enum_type="upload_kind",
                verbose_name="что загружаем",
            ),
        ),
        migrations.AddConstraint(
            model_name="upload",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("seller__isnull", False),
                    ("kind__in", ["ahrefs_batch", "placements", "ahrefs_refdomains", "anchors"]),
                    _connector="OR",
                ),
                name="uploads_seller_check",
                violation_error_message="У прайса и каталога должен быть продавец.",
            ),
        ),
    ]
