# Generated by Django 5.2.17 on 2026-10-05 16:35

import django.db.models.deletion
from django.db import migrations, models

# Рабочие таблицы, которые пишут загрузки (ADR-060): на каждой — два триггера
# журнала. Список повторяет schema.sql 1.18 и tests/test_schema_parity.py.
JOURNAL_TABLES = (
    "auth_user",
    "checks",
    "country_shares",
    "domain_settings",
    "gray_scans",
    "invoice_items",
    "invoices",
    "keyword_positions",
    "keywords",
    "page_type_shares",
    "placement_links",
    "placement_status_changes",
    "placements",
    "product_ref_domains",
    "product_sites",
    "sellers",
    "site_country_metrics",
    "site_list_items",
    "site_lists",
    "site_metrics",
    "site_notes",
    "site_prices",
    "site_status_changes",
    "sites",
    "upload_items",
)

FUNCTION_SQL = """
CREATE FUNCTION log_upload_change() RETURNS trigger
LANGUAGE plpgsql AS $$
DECLARE
    upload bigint := NULLIF(current_setting('seo.upload_id', true), '')::bigint;
BEGIN
    IF upload IS NULL THEN
        RETURN NULL;
    END IF;
    IF TG_OP = 'INSERT' THEN
        INSERT INTO upload_changes (upload_id, table_name, row_id, op)
        VALUES (upload, TG_TABLE_NAME, NEW.id, 'I');
    ELSE
        INSERT INTO upload_changes (upload_id, table_name, row_id, op, before)
        VALUES (upload, TG_TABLE_NAME, OLD.id, left(TG_OP, 1), to_jsonb(OLD));
    END IF;
    RETURN NULL;
END
$$;
"""


def _triggers() -> str:
    return "\n".join(
        f"CREATE TRIGGER {table}_upload_log AFTER INSERT OR DELETE ON {table}"
        " FOR EACH ROW EXECUTE FUNCTION log_upload_change();\n"
        f"CREATE TRIGGER {table}_upload_log_update AFTER UPDATE ON {table}"
        " FOR EACH ROW WHEN (OLD.* IS DISTINCT FROM NEW.*)"
        " EXECUTE FUNCTION log_upload_change();"
        for table in JOURNAL_TABLES
    )


def _drop_triggers() -> str:
    return "\n".join(
        f"DROP TRIGGER {table}_upload_log ON {table};"
        f" DROP TRIGGER {table}_upload_log_update ON {table};"
        for table in JOURNAL_TABLES
    )


class Migration(migrations.Migration):
    dependencies = [
        ("sites", "0020_upload_anchors"),
        ("placements", "0007_invoices"),
        ("keywords", "0004_anchor_shares"),
        ("observability", "0003_api_usage_cost_fractional"),
        ("content", "0007_anchor_recommend"),
    ]

    operations = [
        migrations.AddField(
            model_name="upload",
            name="journaled",
            field=models.BooleanField(db_default=False, default=False, verbose_name="с журналом"),
        ),
        migrations.CreateModel(
            name="UploadChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("table_name", models.TextField(verbose_name="таблица")),
                ("row_id", models.BigIntegerField(verbose_name="строка")),
                ("op", models.TextField(verbose_name="действие")),
                ("before", models.JSONField(blank=True, null=True, verbose_name="было")),
                (
                    "upload",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="changes",
                        to="sites.upload",
                        verbose_name="загрузка",
                    ),
                ),
            ],
            options={
                "verbose_name": "изменение загрузки",
                "verbose_name_plural": "изменения загрузки",
                "db_table": "upload_changes",
                "indexes": [
                    models.Index(
                        fields=["upload", "table_name", "row_id"], name="idx_upload_changes_upload"
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("op__in", ["I", "U", "D"])),
                        name="upload_changes_op_check",
                    )
                ],
            },
        ),
        migrations.RunSQL(sql=FUNCTION_SQL, reverse_sql="DROP FUNCTION log_upload_change()"),
        migrations.RunSQL(sql=_triggers(), reverse_sql=_drop_triggers()),
    ]
