# Заранее посчитанная «площадка на сегодня» (E1-11, ADR-065): дорогие части
# v_site_latest переезжают в таблицу site_latest, представление их читает.
#
# Представления пересоздаются оба: v_product_site_latest стоит на v_site_latest,
# поэтому сначала сносится зависимое. Текст v_product_site_latest не меняется —
# он берёт те же колонки, только теперь они приходят из таблицы.
#
# После создания таблица сразу наполняется: до пересчёта список показал бы
# пустые DR и трафик у всех площадок.

# Generated by Django 5.2.17 on 2026-10-07 14:27

import django.db.models.deletion
from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.migrations.state import StateApps

import config.db

DROP = "DROP VIEW v_product_site_latest; DROP VIEW v_site_latest;"

NEW_VIEWS = """
CREATE VIEW v_site_latest AS
SELECT s.id, s.domain, s.language, s.topics, s.declared_topics,
       s.links_allowed, s.link_type, s.marks_as_ad,
       l.dr, l.organic_traffic, l.total_keywords,
       l.top_geo, l.top_geo_traffic, l.top_geo_at, l.metrics_at,
       l.metrics_trusted, ms.name AS metrics_seller,
       pr.id AS price_id, pr.seller_id AS price_seller_id, ps.name AS price_seller,
       pr.placement_type AS price_type,
       pr.placement_cents, pr.announce_cents, pr.writing_cents,
       pr.currency AS price_currency, pr.checked_at AS prices_at,
       round(pr.placement_cents / eur_rate(pr.currency))::integer AS placement_eur_cents,
       round(pr.writing_cents / eur_rate(pr.currency))::integer AS writing_eur_cents,
       round((pr.placement_cents + coalesce(pr.announce_cents, 0)) / eur_rate(pr.currency))::integer
         AS reference_total_cents,
       l.new_price_id, l.new_price_cents, l.new_price_currency, l.new_price_pending,
       l.cheaper_id, cs.name AS cheaper_seller, l.cheaper_cents, l.cheaper_currency,
       l.cheaper_eur_cents, l.cheaper_pending,
       EXISTS (SELECT 1 FROM site_prices x
               WHERE x.site_id = s.id AND x.reviewed_at IS NULL) AS offers_pending,
       g.ratio AS gray_ratio,
       coalesce(ln.notes, 0) AS notes_count, ln.body AS last_note, ln.created_at AS last_note_at,
       rt.rating_avg, coalesce(rt.rating_count, 0) AS rating_count
FROM sites s
LEFT JOIN site_latest l ON l.site_id = s.id
LEFT JOIN sellers ms ON ms.id = l.metrics_seller_id
LEFT JOIN sellers cs ON cs.id = l.cheaper_seller_id
LEFT JOIN site_prices pr ON pr.id = s.price_id
LEFT JOIN sellers ps ON ps.id = pr.seller_id
LEFT JOIN LATERAL (SELECT * FROM gray_scans x WHERE x.site_id = s.id
                   ORDER BY checked_at DESC LIMIT 1) g ON true
LEFT JOIN (SELECT DISTINCT ON (x.site_id) x.site_id, x.body, x.created_at,
                  count(*) OVER (PARTITION BY x.site_id) AS notes
           FROM site_notes x
           ORDER BY x.site_id, x.created_at DESC, x.id DESC) ln ON ln.site_id = s.id
LEFT JOIN (SELECT x.site_id, round(avg(x.value), 1) AS rating_avg,
                  count(*) AS rating_count
           FROM site_ratings x
           GROUP BY x.site_id) rt ON rt.site_id = s.id
WHERE NOT s.is_deleted;
CREATE VIEW v_product_site_latest AS
SELECT ps.id, ps.product_id, ps.site_id, ps.status, ps.comment, ps.imported_undecided,
       l.domain, l.language, l.topics, l.declared_topics,
       l.links_allowed, l.link_type, l.marks_as_ad,
       l.dr, l.organic_traffic, l.total_keywords, l.top_geo, l.top_geo_traffic, l.top_geo_at,
       l.metrics_at,
       l.metrics_trusted, l.metrics_seller,
       l.price_id, l.price_seller_id, l.price_seller, l.price_type,
       l.placement_cents, l.announce_cents, l.writing_cents, l.price_currency, l.prices_at,
       l.placement_eur_cents, l.writing_eur_cents, l.reference_total_cents,
       CASE WHEN l.price_type = 'link_insertion' THEN NULL
            ELSE l.writing_eur_cents IS NULL OR l.writing_eur_cents > w.writing_cents END AS we_write,
       l.reference_total_cents
         + CASE WHEN w.writing_cents IS NULL THEN NULL
                WHEN l.writing_eur_cents <= w.writing_cents THEN l.writing_eur_cents
                ELSE 0 END AS expected_spend_cents,
       l.new_price_id, l.new_price_cents, l.new_price_currency, l.new_price_pending,
       l.cheaper_id, l.cheaper_seller, l.cheaper_cents, l.cheaper_currency,
       l.cheaper_eur_cents, l.cheaper_pending, l.offers_pending,
       l.gray_ratio,
       l.notes_count, l.last_note, l.last_note_at,
       l.rating_avg, l.rating_count,
       a.verdict AS last_verdict, a.score AS last_score, a.created_at AS audited_at,
       pp.published AS placements_published,
       op.names AS other_products
FROM product_sites ps
JOIN v_site_latest l ON l.id = ps.site_id
LEFT JOIN LATERAL (SELECT (x.value->>'writing_eur')::integer * 100 AS writing_cents
                   FROM domain_settings x
                   WHERE x.key = 'PRICE_REFERENCE'
                     AND (x.product_id = ps.product_id OR x.product_id IS NULL)
                   ORDER BY x.product_id NULLS LAST LIMIT 1) w ON true
LEFT JOIN LATERAL (SELECT * FROM site_audits x
                   WHERE x.site_id = ps.site_id AND x.product_id = ps.product_id
                   ORDER BY created_at DESC LIMIT 1) a ON true
LEFT JOIN LATERAL (SELECT count(*) AS published FROM placements x
                   WHERE x.site_id = ps.site_id AND x.product_id = ps.product_id
                     AND x.status = 'placed') pp ON true
LEFT JOIN LATERAL (SELECT array_agg(pr.name ORDER BY pr.name) AS names
                   FROM products pr
                   WHERE pr.id <> ps.product_id
                     AND EXISTS (SELECT 1 FROM placements x
                                 WHERE x.site_id = ps.site_id AND x.product_id = pr.id)) op ON true;
"""

OLD_VIEWS = """
CREATE VIEW v_site_latest AS
SELECT s.id, s.domain, s.language, s.topics, s.declared_topics,
       s.links_allowed, s.link_type, s.marks_as_ad,
       m.dr, m.organic_traffic, m.total_keywords,
       tg.top_geo, tg.top_geo_traffic, tg.checked_at AS top_geo_at, m.checked_at AS metrics_at,
       m.trusted AS metrics_trusted, ms.name AS metrics_seller,
       pr.id AS price_id, pr.seller_id AS price_seller_id, ps.name AS price_seller,
       pr.placement_type AS price_type,
       pr.placement_cents, pr.announce_cents, pr.writing_cents,
       pr.currency AS price_currency, pr.checked_at AS prices_at,
       round(pr.placement_cents / eur_rate(pr.currency))::integer AS placement_eur_cents,
       round(pr.writing_cents / eur_rate(pr.currency))::integer AS writing_eur_cents,
       round((pr.placement_cents + coalesce(pr.announce_cents, 0)) / eur_rate(pr.currency))::integer
         AS reference_total_cents,
       np.id AS new_price_id, np.placement_cents AS new_price_cents,
       np.currency AS new_price_currency, np.reviewed_at IS NULL AS new_price_pending,
       ch.id AS cheaper_id, ch.seller AS cheaper_seller, ch.placement_cents AS cheaper_cents,
       ch.currency AS cheaper_currency, ch.placement_eur_cents AS cheaper_eur_cents,
       ch.reviewed_at IS NULL AS cheaper_pending,
       EXISTS (SELECT 1 FROM site_prices x
               WHERE x.site_id = s.id AND x.reviewed_at IS NULL) AS offers_pending,
       g.ratio AS gray_ratio,
       coalesce(ln.notes, 0) AS notes_count, ln.body AS last_note, ln.created_at AS last_note_at,
       rt.rating_avg, coalesce(rt.rating_count, 0) AS rating_count
FROM sites s
LEFT JOIN LATERAL (SELECT x.dr, x.organic_traffic, x.total_keywords, x.checked_at,
                          x.seller_id, x.seller_id IS NULL OR xs.metrics_trusted AS trusted
                   FROM site_metrics x LEFT JOIN sellers xs ON xs.id = x.seller_id
                   WHERE x.site_id = s.id
                   ORDER BY x.seller_id IS NULL OR xs.metrics_trusted DESC, x.checked_at DESC
                   LIMIT 1) m ON true
LEFT JOIN sellers ms ON ms.id = m.seller_id
LEFT JOIN LATERAL (SELECT x.top_geo, x.top_geo_traffic, x.checked_at
                   FROM site_metrics x LEFT JOIN sellers xs ON xs.id = x.seller_id
                   WHERE x.site_id = s.id AND x.top_geo IS NOT NULL
                   ORDER BY x.seller_id IS NULL OR xs.metrics_trusted DESC, x.checked_at DESC
                   LIMIT 1) tg ON true
LEFT JOIN site_prices pr ON pr.id = s.price_id
LEFT JOIN sellers ps ON ps.id = pr.seller_id
LEFT JOIN LATERAL (SELECT o.id, o.placement_cents, o.currency, o.reviewed_at
                   FROM v_site_offers o
                   WHERE o.site_id = s.id AND o.seller_id = pr.seller_id
                     AND o.placement_type = pr.placement_type AND o.id <> pr.id) np ON true
LEFT JOIN LATERAL (SELECT o.id, o.seller, o.placement_cents, o.currency, o.placement_eur_cents,
                          o.reviewed_at
                   FROM v_site_offers o
                   WHERE o.site_id = s.id AND o.placement_type = pr.placement_type
                     AND o.seller_id <> pr.seller_id
                     AND o.placement_eur_cents < round(pr.placement_cents / eur_rate(pr.currency))
                   ORDER BY o.placement_eur_cents, o.id LIMIT 1) ch ON true
LEFT JOIN LATERAL (SELECT * FROM gray_scans x WHERE x.site_id = s.id
                   ORDER BY checked_at DESC LIMIT 1) g ON true
LEFT JOIN (SELECT DISTINCT ON (x.site_id) x.site_id, x.body, x.created_at,
                  count(*) OVER (PARTITION BY x.site_id) AS notes
           FROM site_notes x
           ORDER BY x.site_id, x.created_at DESC, x.id DESC) ln ON ln.site_id = s.id
LEFT JOIN (SELECT x.site_id, round(avg(x.value), 1) AS rating_avg,
                  count(*) AS rating_count
           FROM site_ratings x
           GROUP BY x.site_id) rt ON rt.site_id = s.id
WHERE NOT s.is_deleted;
CREATE VIEW v_product_site_latest AS
SELECT ps.id, ps.product_id, ps.site_id, ps.status, ps.comment, ps.imported_undecided,
       l.domain, l.language, l.topics, l.declared_topics,
       l.links_allowed, l.link_type, l.marks_as_ad,
       l.dr, l.organic_traffic, l.total_keywords, l.top_geo, l.top_geo_traffic, l.top_geo_at,
       l.metrics_at,
       l.metrics_trusted, l.metrics_seller,
       l.price_id, l.price_seller_id, l.price_seller, l.price_type,
       l.placement_cents, l.announce_cents, l.writing_cents, l.price_currency, l.prices_at,
       l.placement_eur_cents, l.writing_eur_cents, l.reference_total_cents,
       CASE WHEN l.price_type = 'link_insertion' THEN NULL
            ELSE l.writing_eur_cents IS NULL OR l.writing_eur_cents > w.writing_cents END AS we_write,
       l.reference_total_cents
         + CASE WHEN w.writing_cents IS NULL THEN NULL
                WHEN l.writing_eur_cents <= w.writing_cents THEN l.writing_eur_cents
                ELSE 0 END AS expected_spend_cents,
       l.new_price_id, l.new_price_cents, l.new_price_currency, l.new_price_pending,
       l.cheaper_id, l.cheaper_seller, l.cheaper_cents, l.cheaper_currency,
       l.cheaper_eur_cents, l.cheaper_pending, l.offers_pending,
       l.gray_ratio,
       l.notes_count, l.last_note, l.last_note_at,
       l.rating_avg, l.rating_count,
       a.verdict AS last_verdict, a.score AS last_score, a.created_at AS audited_at,
       pp.published AS placements_published,
       op.names AS other_products
FROM product_sites ps
JOIN v_site_latest l ON l.id = ps.site_id
LEFT JOIN LATERAL (SELECT (x.value->>'writing_eur')::integer * 100 AS writing_cents
                   FROM domain_settings x
                   WHERE x.key = 'PRICE_REFERENCE'
                     AND (x.product_id = ps.product_id OR x.product_id IS NULL)
                   ORDER BY x.product_id NULLS LAST LIMIT 1) w ON true
LEFT JOIN LATERAL (SELECT * FROM site_audits x
                   WHERE x.site_id = ps.site_id AND x.product_id = ps.product_id
                   ORDER BY created_at DESC LIMIT 1) a ON true
LEFT JOIN LATERAL (SELECT count(*) AS published FROM placements x
                   WHERE x.site_id = ps.site_id AND x.product_id = ps.product_id
                     AND x.status = 'placed') pp ON true
LEFT JOIN LATERAL (SELECT array_agg(pr.name ORDER BY pr.name) AS names
                   FROM products pr
                   WHERE pr.id <> ps.product_id
                     AND EXISTS (SELECT 1 FROM placements x
                                 WHERE x.site_id = ps.site_id AND x.product_id = pr.id)) op ON true;
"""


def fill(apps: StateApps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    """Наполнить копию теми же правилами, что считает `apps.sites.latest`."""
    from apps.sites import latest

    latest.refresh_all()


def clear(apps: StateApps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    apps.get_model("sites", "SiteLatest").objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("sites", "0024_site_ratings"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteLatest",
            fields=[
                (
                    "site",
                    models.OneToOneField(
                        db_column="site_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="latest",
                        serialize=False,
                        to="sites.site",
                        verbose_name="площадка",
                    ),
                ),
                ("dr", models.SmallIntegerField(null=True, verbose_name="DR")),
                ("organic_traffic", models.IntegerField(null=True, verbose_name="трафик")),
                (
                    "total_keywords",
                    models.IntegerField(null=True, verbose_name="ключей в органике"),
                ),
                ("metrics_at", models.DateTimeField(null=True, verbose_name="дата метрик")),
                (
                    "metrics_trusted",
                    models.BooleanField(null=True, verbose_name="метрики доверенного источника"),
                ),
                ("top_geo", models.TextField(null=True, verbose_name="основное гео")),
                (
                    "top_geo_traffic",
                    models.IntegerField(null=True, verbose_name="трафик основного гео"),
                ),
                ("top_geo_at", models.DateTimeField(null=True, verbose_name="дата замера гео")),
                ("new_price_id", models.BigIntegerField(null=True, verbose_name="новая цена, id")),
                (
                    "new_price_cents",
                    models.IntegerField(null=True, verbose_name="новая цена, центы"),
                ),
                (
                    "new_price_currency",
                    models.CharField(max_length=3, null=True, verbose_name="валюта новой цены"),
                ),
                (
                    "new_price_pending",
                    models.BooleanField(null=True, verbose_name="новая цена не разобрана"),
                ),
                ("cheaper_id", models.BigIntegerField(null=True, verbose_name="дешевле, id")),
                ("cheaper_cents", models.IntegerField(null=True, verbose_name="дешевле, центы")),
                (
                    "cheaper_currency",
                    models.CharField(max_length=3, null=True, verbose_name="валюта дешёвого"),
                ),
                (
                    "cheaper_eur_cents",
                    models.IntegerField(null=True, verbose_name="дешевле, евроценты"),
                ),
                (
                    "cheaper_pending",
                    models.BooleanField(null=True, verbose_name="дешёвое не разобрано"),
                ),
                (
                    "computed_at",
                    models.DateTimeField(db_default=config.db.PgNow(), verbose_name="пересчитано"),
                ),
                (
                    "cheaper_seller",
                    models.ForeignKey(
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="sites.seller",
                        verbose_name="дешевле у продавца",
                    ),
                ),
                (
                    "metrics_seller",
                    models.ForeignKey(
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="sites.seller",
                        verbose_name="метрики со слов продавца",
                    ),
                ),
            ],
            options={
                "verbose_name": "посчитанная площадка",
                "verbose_name_plural": "посчитанные площадки",
                "db_table": "site_latest",
                "indexes": [
                    models.Index(
                        models.OrderBy(models.F("dr"), descending=True, nulls_last=True),
                        models.F("site"),
                        name="idx_site_latest_dr",
                    )
                ],
            },
        ),
        migrations.RunSQL(DROP + NEW_VIEWS, DROP + OLD_VIEWS),
        migrations.RunPython(fill, clear),
    ]
