# Оценка продавца звёздочкой (E1-24): устроена как оценка площадки (ADR-064) —
# одна строка на пару человек × продавец, история не ведётся. Представления
# не трогаем: среднее у продавцов считается на месте, их полсотни.

# Generated by Django 5.2.17 on 2026-10-07 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import config.db


class Migration(migrations.Migration):
    dependencies = [
        ("sites", "0025_site_latest"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SellerRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("value", models.SmallIntegerField(verbose_name="оценка")),
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=config.db.PgNow(), verbose_name="первая оценка"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(db_default=config.db.PgNow(), verbose_name="изменена"),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="sites.seller",
                        verbose_name="продавец",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seller_ratings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="кто оценил",
                    ),
                ),
            ],
            options={
                "verbose_name": "оценка продавца",
                "verbose_name_plural": "оценки продавцов",
                "db_table": "seller_ratings",
                "indexes": [models.Index(fields=["seller"], name="idx_seller_ratings_seller")],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("seller", "user"), name="seller_ratings_seller_user_key"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("value__gte", 1), ("value__lte", 5)),
                        name="seller_ratings_value_check",
                        violation_error_message="Оценка — от 1 до 5 звёзд.",
                    ),
                ],
            },
        ),
    ]
