# Generated by Django 5.2.17 on 2026-10-03 19:47

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models

import config.db


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SavedFilter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("screen", models.TextField(verbose_name="список")),
                ("name", models.TextField(verbose_name="название")),
                ("query", models.TextField(verbose_name="фильтры")),
                (
                    "created_at",
                    models.DateTimeField(db_default=config.db.PgNow(), verbose_name="создан"),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="удалён")),
                (
                    "user",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="saved_filters",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "набор фильтров",
                "verbose_name_plural": "наборы фильтров",
                "db_table": "saved_filters",
                "constraints": [
                    models.UniqueConstraint(
                        models.F("user"),
                        models.F("screen"),
                        django.db.models.functions.text.Lower("name"),
                        condition=models.Q(("deleted_at__isnull", True)),
                        name="saved_filters_name_key",
                        violation_error_message="Набор с таким названием уже есть.",
                    )
                ],
            },
        ),
    ]
