# Generated by Django 5.2.17 on 2026-10-05 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import config.db


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("sites", "0018_uploads_placements_refdomains"),
        ("workspace", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSettings",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        primary_key=True,
                        related_name="workspace_settings",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="пользователь",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(db_default=config.db.PgNow(), verbose_name="изменено"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="sites.product",
                        verbose_name="рабочий продукт",
                    ),
                ),
            ],
            options={
                "verbose_name": "настройки пользователя",
                "verbose_name_plural": "настройки пользователей",
                "db_table": "user_settings",
            },
        ),
    ]
