# Generated by Django 5.2.17 on 2026-10-05 10:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workspace", "0002_user_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersettings",
            name="card_closed",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                db_default=models.Value(
                    [],
                    output_field=django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), size=None
                    ),
                ),
                default=list,
                size=None,
                verbose_name="свёрнутые разделы карточки",
            ),
        ),
    ]
