# Generated by Django 5.2.17 on 2026-10-06 16:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workspace", "0003_user_settings_card_closed"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersettings",
            name="filters",
            field=models.JSONField(
                db_default=models.Value({}, output_field=models.JSONField()),
                default=dict,
                verbose_name="выбор фильтров",
            ),
        ),
    ]
